version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_APP_API_URL=${VITE_APP_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-net

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notesdb
    depends_on:
      - mongo
    networks:
      - mern-net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-net

volumes:
  mongo_data:

networks:
  mern-net:
